//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Bug_Mapping : EntityTypeConfiguration<Bug>
    {
        public Bug_Mapping()
        {                        
              this.HasKey(t => t.BugID);        
              this.ToTable("Bug");
              this.Property(t => t.BugID).HasColumnName("BugID");
              this.Property(t => t.HSD).HasColumnName("HSD").IsRequired();
              this.Property(t => t.CSP).HasColumnName("CSP").IsRequired();
              this.Property(t => t.WINQUAL).HasColumnName("WINQUAL").IsRequired();
              this.Property(t => t.MANAGEPRO).HasColumnName("MANAGEPRO").IsRequired();
         }
    }
}
