//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Driver_Config
    {
        public Driver_Config()
        {
            this.Test_Config = new HashSet<Test_Config>();
        }
    
        public int DriverConfigID { get; set; }
        public string Team { get; set; }
        public string BKC_Version { get; set; }
        public string SoftAP { get; set; }
        public string BT_Driver { get; set; }
        public string WiFi_Driver { get; set; }
        public string NFC_Driver { get; set; }
        public string GPS_Driver { get; set; }
    
        public virtual ICollection<Test_Config> Test_Config { get; set; }
    }
}
