//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Driver_Config_Mapping : EntityTypeConfiguration<Driver_Config>
    {
        public Driver_Config_Mapping()
        {                        
              this.HasKey(t => t.DriverConfigID);        
              this.ToTable("Driver_Config");
              this.Property(t => t.DriverConfigID).HasColumnName("DriverConfigID");
              this.Property(t => t.Team).HasColumnName("Team").IsRequired();
              this.Property(t => t.BKC_Version).HasColumnName("BKC_Version").IsRequired();
              this.Property(t => t.SoftAP).HasColumnName("SoftAP").IsRequired();
              this.Property(t => t.BT_Driver).HasColumnName("BT_Driver").IsRequired();
              this.Property(t => t.WiFi_Driver).HasColumnName("WiFi_Driver").IsRequired();
              this.Property(t => t.NFC_Driver).HasColumnName("NFC_Driver").IsRequired();
              this.Property(t => t.GPS_Driver).HasColumnName("GPS_Driver").IsRequired();
         }
    }
}
