//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Packages = new HashSet<Package>();
        }
    
        public int UserID { get; set; }
        public string IDsid { get; set; }
        public System.DateTime Last_AccessTime { get; set; }
        public string EAM_role { get; set; }
        public string CDIS_email { get; set; }
    
        public virtual ICollection<Package> Packages { get; set; }
    }
}
