//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Login_Mapping : EntityTypeConfiguration<Login>
    {
        public Login_Mapping()
        {                        
              this.HasKey(t => t.UserID);        
              this.ToTable("Login");
              this.Property(t => t.UserID).HasColumnName("UserID");
              this.Property(t => t.IDsid).HasColumnName("IDsid").IsRequired().HasMaxLength(500);
              this.Property(t => t.Last_AccessTime).HasColumnName("Last_AccessTime");
              this.Property(t => t.EAM_role).HasColumnName("EAM_role").IsRequired().HasMaxLength(500);
              this.Property(t => t.CDIS_email).HasColumnName("CDIS_email").IsRequired().HasMaxLength(500);
         }
    }
}
