//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int PackageID { get; set; }
        public int ConfigNumID { get; set; }
        public int UserID { get; set; }
        public string Checksum { get; set; }
        public System.DateTime Date_Uploaded { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string TestResult_Summary { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Test_Config Test_Config { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
