//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Group
    {
        public Project_Group()
        {
            this.Components = new HashSet<Component>();
        }
    
        public int Project_GroupID { get; set; }
        public string Name { get; set; }
        public int ConfigNumID { get; set; }
    
        public virtual ICollection<Component> Components { get; set; }
        public virtual Test_Config Test_Config { get; set; }
    }
}
