//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tsiewhckweb.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Test_Config_Mapping : EntityTypeConfiguration<Test_Config>
    {
        public Test_Config_Mapping()
        {                        
              this.HasKey(t => t.ConfigNumID);        
              this.ToTable("Test_Config");
              this.Property(t => t.ConfigNumID).HasColumnName("ConfigNumID").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.MachineConfigID).HasColumnName("MachineConfigID");
              this.Property(t => t.DriverConfigID).HasColumnName("DriverConfigID");
              this.HasRequired(t => t.Driver_Config).WithMany(t => t.Test_Config).HasForeignKey(d => d.DriverConfigID);
              this.HasRequired(t => t.Machine_Config).WithMany(t => t.Test_Config).HasForeignKey(d => d.MachineConfigID);
         }
    }
}
