//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Result_Bug", "Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Bug), "Result", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Result), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Component_Project_Group", "Project_Group", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Project_Group), "Component", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Component), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_TestCase_Component", "Component", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Component), "TestCase", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.TestCase), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Test_Config_Driver_Config", "Driver_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Driver_Config), "Test_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Test_Config), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Package_Login", "Login", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Login), "Package", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Package), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Test_Config_Machine_Config", "Machine_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Machine_Config), "Test_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Test_Config), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Package_Test_Config", "Test_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Test_Config), "Package", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Package), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Result_Package", "Package", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Package), "Result", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Result), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Project_Group_Test_Config", "Test_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.Test_Config), "Project_Group", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Project_Group), true)]
[assembly: EdmRelationshipAttribute("tsiewhckweb.Models", "FK_Result_TestCase", "TestCase", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(tsiewhckweb.Models.TestCase), "Result", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(tsiewhckweb.Models.Result), true)]

#endregion

namespace tsiewhckweb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class tsiewhckwebEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new tsiewhckwebEntities object using the connection string found in the 'tsiewhckwebEntities' section of the application configuration file.
        /// </summary>
        public tsiewhckwebEntities() : base("name=tsiewhckwebEntities", "tsiewhckwebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tsiewhckwebEntities object.
        /// </summary>
        public tsiewhckwebEntities(string connectionString) : base(connectionString, "tsiewhckwebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tsiewhckwebEntities object.
        /// </summary>
        public tsiewhckwebEntities(EntityConnection connection) : base(connection, "tsiewhckwebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bug> Bugs
        {
            get
            {
                if ((_Bugs == null))
                {
                    _Bugs = base.CreateObjectSet<Bug>("Bugs");
                }
                return _Bugs;
            }
        }
        private ObjectSet<Bug> _Bugs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Component> Components
        {
            get
            {
                if ((_Components == null))
                {
                    _Components = base.CreateObjectSet<Component>("Components");
                }
                return _Components;
            }
        }
        private ObjectSet<Component> _Components;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Driver_Config> Driver_Config
        {
            get
            {
                if ((_Driver_Config == null))
                {
                    _Driver_Config = base.CreateObjectSet<Driver_Config>("Driver_Config");
                }
                return _Driver_Config;
            }
        }
        private ObjectSet<Driver_Config> _Driver_Config;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Login> Logins
        {
            get
            {
                if ((_Logins == null))
                {
                    _Logins = base.CreateObjectSet<Login>("Logins");
                }
                return _Logins;
            }
        }
        private ObjectSet<Login> _Logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Machine_Config> Machine_Config
        {
            get
            {
                if ((_Machine_Config == null))
                {
                    _Machine_Config = base.CreateObjectSet<Machine_Config>("Machine_Config");
                }
                return _Machine_Config;
            }
        }
        private ObjectSet<Machine_Config> _Machine_Config;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Package> Packages
        {
            get
            {
                if ((_Packages == null))
                {
                    _Packages = base.CreateObjectSet<Package>("Packages");
                }
                return _Packages;
            }
        }
        private ObjectSet<Package> _Packages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project_Group> Project_Group
        {
            get
            {
                if ((_Project_Group == null))
                {
                    _Project_Group = base.CreateObjectSet<Project_Group>("Project_Group");
                }
                return _Project_Group;
            }
        }
        private ObjectSet<Project_Group> _Project_Group;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Result> Results
        {
            get
            {
                if ((_Results == null))
                {
                    _Results = base.CreateObjectSet<Result>("Results");
                }
                return _Results;
            }
        }
        private ObjectSet<Result> _Results;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test_Config> Test_Config
        {
            get
            {
                if ((_Test_Config == null))
                {
                    _Test_Config = base.CreateObjectSet<Test_Config>("Test_Config");
                }
                return _Test_Config;
            }
        }
        private ObjectSet<Test_Config> _Test_Config;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestCase> TestCases
        {
            get
            {
                if ((_TestCases == null))
                {
                    _TestCases = base.CreateObjectSet<TestCase>("TestCases");
                }
                return _TestCases;
            }
        }
        private ObjectSet<TestCase> _TestCases;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bugs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBugs(Bug bug)
        {
            base.AddObject("Bugs", bug);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Components EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComponents(Component component)
        {
            base.AddObject("Components", component);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Driver_Config EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDriver_Config(Driver_Config driver_Config)
        {
            base.AddObject("Driver_Config", driver_Config);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogins(Login login)
        {
            base.AddObject("Logins", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Machine_Config EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMachine_Config(Machine_Config machine_Config)
        {
            base.AddObject("Machine_Config", machine_Config);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Packages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPackages(Package package)
        {
            base.AddObject("Packages", package);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Project_Group EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProject_Group(Project_Group project_Group)
        {
            base.AddObject("Project_Group", project_Group);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Results EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResults(Result result)
        {
            base.AddObject("Results", result);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Test_Config EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTest_Config(Test_Config test_Config)
        {
            base.AddObject("Test_Config", test_Config);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestCases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestCases(TestCase testCase)
        {
            base.AddObject("TestCases", testCase);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Bug")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bug : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bug object.
        /// </summary>
        /// <param name="bugID">Initial value of the BugID property.</param>
        /// <param name="hSD">Initial value of the HSD property.</param>
        /// <param name="cSP">Initial value of the CSP property.</param>
        /// <param name="wINQUAL">Initial value of the WINQUAL property.</param>
        /// <param name="mANAGEPRO">Initial value of the MANAGEPRO property.</param>
        public static Bug CreateBug(global::System.Int32 bugID, global::System.String hSD, global::System.String cSP, global::System.String wINQUAL, global::System.String mANAGEPRO)
        {
            Bug bug = new Bug();
            bug.BugID = bugID;
            bug.HSD = hSD;
            bug.CSP = cSP;
            bug.WINQUAL = wINQUAL;
            bug.MANAGEPRO = mANAGEPRO;
            return bug;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BugID
        {
            get
            {
                return _BugID;
            }
            set
            {
                if (_BugID != value)
                {
                    OnBugIDChanging(value);
                    ReportPropertyChanging("BugID");
                    _BugID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BugID");
                    OnBugIDChanged();
                }
            }
        }
        private global::System.Int32 _BugID;
        partial void OnBugIDChanging(global::System.Int32 value);
        partial void OnBugIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HSD
        {
            get
            {
                return _HSD;
            }
            set
            {
                OnHSDChanging(value);
                ReportPropertyChanging("HSD");
                _HSD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HSD");
                OnHSDChanged();
            }
        }
        private global::System.String _HSD;
        partial void OnHSDChanging(global::System.String value);
        partial void OnHSDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CSP
        {
            get
            {
                return _CSP;
            }
            set
            {
                OnCSPChanging(value);
                ReportPropertyChanging("CSP");
                _CSP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CSP");
                OnCSPChanged();
            }
        }
        private global::System.String _CSP;
        partial void OnCSPChanging(global::System.String value);
        partial void OnCSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WINQUAL
        {
            get
            {
                return _WINQUAL;
            }
            set
            {
                OnWINQUALChanging(value);
                ReportPropertyChanging("WINQUAL");
                _WINQUAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WINQUAL");
                OnWINQUALChanged();
            }
        }
        private global::System.String _WINQUAL;
        partial void OnWINQUALChanging(global::System.String value);
        partial void OnWINQUALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MANAGEPRO
        {
            get
            {
                return _MANAGEPRO;
            }
            set
            {
                OnMANAGEPROChanging(value);
                ReportPropertyChanging("MANAGEPRO");
                _MANAGEPRO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MANAGEPRO");
                OnMANAGEPROChanged();
            }
        }
        private global::System.String _MANAGEPRO;
        partial void OnMANAGEPROChanging(global::System.String value);
        partial void OnMANAGEPROChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Result_Bug", "Result")]
        public EntityCollection<Result> Results
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Result>("tsiewhckweb.Models.FK_Result_Bug", "Result");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Result>("tsiewhckweb.Models.FK_Result_Bug", "Result", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Component")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Component : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Component object.
        /// </summary>
        /// <param name="componentID">Initial value of the ComponentID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="project_GroupID">Initial value of the Project_GroupID property.</param>
        public static Component CreateComponent(global::System.Int32 componentID, global::System.String name, global::System.Int32 project_GroupID)
        {
            Component component = new Component();
            component.ComponentID = componentID;
            component.Name = name;
            component.Project_GroupID = project_GroupID;
            return component;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComponentID
        {
            get
            {
                return _ComponentID;
            }
            set
            {
                if (_ComponentID != value)
                {
                    OnComponentIDChanging(value);
                    ReportPropertyChanging("ComponentID");
                    _ComponentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ComponentID");
                    OnComponentIDChanged();
                }
            }
        }
        private global::System.Int32 _ComponentID;
        partial void OnComponentIDChanging(global::System.Int32 value);
        partial void OnComponentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Project_GroupID
        {
            get
            {
                return _Project_GroupID;
            }
            set
            {
                OnProject_GroupIDChanging(value);
                ReportPropertyChanging("Project_GroupID");
                _Project_GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Project_GroupID");
                OnProject_GroupIDChanged();
            }
        }
        private global::System.Int32 _Project_GroupID;
        partial void OnProject_GroupIDChanging(global::System.Int32 value);
        partial void OnProject_GroupIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Component_Project_Group", "Project_Group")]
        public Project_Group Project_Group
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project_Group>("tsiewhckweb.Models.FK_Component_Project_Group", "Project_Group").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project_Group>("tsiewhckweb.Models.FK_Component_Project_Group", "Project_Group").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project_Group> Project_GroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project_Group>("tsiewhckweb.Models.FK_Component_Project_Group", "Project_Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project_Group>("tsiewhckweb.Models.FK_Component_Project_Group", "Project_Group", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_TestCase_Component", "TestCase")]
        public EntityCollection<TestCase> TestCases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TestCase>("tsiewhckweb.Models.FK_TestCase_Component", "TestCase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TestCase>("tsiewhckweb.Models.FK_TestCase_Component", "TestCase", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Driver_Config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Driver_Config : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Driver_Config object.
        /// </summary>
        /// <param name="driverConfigID">Initial value of the DriverConfigID property.</param>
        /// <param name="team">Initial value of the Team property.</param>
        /// <param name="bKC_Version">Initial value of the BKC_Version property.</param>
        /// <param name="softAP">Initial value of the SoftAP property.</param>
        /// <param name="bT_Driver">Initial value of the BT_Driver property.</param>
        /// <param name="wiFi_Driver">Initial value of the WiFi_Driver property.</param>
        /// <param name="nFC_Driver">Initial value of the NFC_Driver property.</param>
        /// <param name="gPS_Driver">Initial value of the GPS_Driver property.</param>
        public static Driver_Config CreateDriver_Config(global::System.Int32 driverConfigID, global::System.String team, global::System.String bKC_Version, global::System.String softAP, global::System.String bT_Driver, global::System.String wiFi_Driver, global::System.String nFC_Driver, global::System.String gPS_Driver)
        {
            Driver_Config driver_Config = new Driver_Config();
            driver_Config.DriverConfigID = driverConfigID;
            driver_Config.Team = team;
            driver_Config.BKC_Version = bKC_Version;
            driver_Config.SoftAP = softAP;
            driver_Config.BT_Driver = bT_Driver;
            driver_Config.WiFi_Driver = wiFi_Driver;
            driver_Config.NFC_Driver = nFC_Driver;
            driver_Config.GPS_Driver = gPS_Driver;
            return driver_Config;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DriverConfigID
        {
            get
            {
                return _DriverConfigID;
            }
            set
            {
                if (_DriverConfigID != value)
                {
                    OnDriverConfigIDChanging(value);
                    ReportPropertyChanging("DriverConfigID");
                    _DriverConfigID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DriverConfigID");
                    OnDriverConfigIDChanged();
                }
            }
        }
        private global::System.Int32 _DriverConfigID;
        partial void OnDriverConfigIDChanging(global::System.Int32 value);
        partial void OnDriverConfigIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Team
        {
            get
            {
                return _Team;
            }
            set
            {
                OnTeamChanging(value);
                ReportPropertyChanging("Team");
                _Team = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Team");
                OnTeamChanged();
            }
        }
        private global::System.String _Team;
        partial void OnTeamChanging(global::System.String value);
        partial void OnTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BKC_Version
        {
            get
            {
                return _BKC_Version;
            }
            set
            {
                OnBKC_VersionChanging(value);
                ReportPropertyChanging("BKC_Version");
                _BKC_Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BKC_Version");
                OnBKC_VersionChanged();
            }
        }
        private global::System.String _BKC_Version;
        partial void OnBKC_VersionChanging(global::System.String value);
        partial void OnBKC_VersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SoftAP
        {
            get
            {
                return _SoftAP;
            }
            set
            {
                OnSoftAPChanging(value);
                ReportPropertyChanging("SoftAP");
                _SoftAP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SoftAP");
                OnSoftAPChanged();
            }
        }
        private global::System.String _SoftAP;
        partial void OnSoftAPChanging(global::System.String value);
        partial void OnSoftAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BT_Driver
        {
            get
            {
                return _BT_Driver;
            }
            set
            {
                OnBT_DriverChanging(value);
                ReportPropertyChanging("BT_Driver");
                _BT_Driver = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BT_Driver");
                OnBT_DriverChanged();
            }
        }
        private global::System.String _BT_Driver;
        partial void OnBT_DriverChanging(global::System.String value);
        partial void OnBT_DriverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WiFi_Driver
        {
            get
            {
                return _WiFi_Driver;
            }
            set
            {
                OnWiFi_DriverChanging(value);
                ReportPropertyChanging("WiFi_Driver");
                _WiFi_Driver = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WiFi_Driver");
                OnWiFi_DriverChanged();
            }
        }
        private global::System.String _WiFi_Driver;
        partial void OnWiFi_DriverChanging(global::System.String value);
        partial void OnWiFi_DriverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NFC_Driver
        {
            get
            {
                return _NFC_Driver;
            }
            set
            {
                OnNFC_DriverChanging(value);
                ReportPropertyChanging("NFC_Driver");
                _NFC_Driver = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NFC_Driver");
                OnNFC_DriverChanged();
            }
        }
        private global::System.String _NFC_Driver;
        partial void OnNFC_DriverChanging(global::System.String value);
        partial void OnNFC_DriverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GPS_Driver
        {
            get
            {
                return _GPS_Driver;
            }
            set
            {
                OnGPS_DriverChanging(value);
                ReportPropertyChanging("GPS_Driver");
                _GPS_Driver = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GPS_Driver");
                OnGPS_DriverChanged();
            }
        }
        private global::System.String _GPS_Driver;
        partial void OnGPS_DriverChanging(global::System.String value);
        partial void OnGPS_DriverChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Test_Config_Driver_Config", "Test_Config")]
        public EntityCollection<Test_Config> Test_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Test_Config>("tsiewhckweb.Models.FK_Test_Config_Driver_Config", "Test_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Test_Config>("tsiewhckweb.Models.FK_Test_Config_Driver_Config", "Test_Config", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Login object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="iDsid">Initial value of the IDsid property.</param>
        /// <param name="last_AccessTime">Initial value of the Last_AccessTime property.</param>
        /// <param name="eAM_role">Initial value of the EAM_role property.</param>
        /// <param name="cDIS_email">Initial value of the CDIS_email property.</param>
        public static Login CreateLogin(global::System.Int32 userID, global::System.String iDsid, global::System.DateTime last_AccessTime, global::System.String eAM_role, global::System.String cDIS_email)
        {
            Login login = new Login();
            login.UserID = userID;
            login.IDsid = iDsid;
            login.Last_AccessTime = last_AccessTime;
            login.EAM_role = eAM_role;
            login.CDIS_email = cDIS_email;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IDsid
        {
            get
            {
                return _IDsid;
            }
            set
            {
                OnIDsidChanging(value);
                ReportPropertyChanging("IDsid");
                _IDsid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IDsid");
                OnIDsidChanged();
            }
        }
        private global::System.String _IDsid;
        partial void OnIDsidChanging(global::System.String value);
        partial void OnIDsidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Last_AccessTime
        {
            get
            {
                return _Last_AccessTime;
            }
            set
            {
                OnLast_AccessTimeChanging(value);
                ReportPropertyChanging("Last_AccessTime");
                _Last_AccessTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Last_AccessTime");
                OnLast_AccessTimeChanged();
            }
        }
        private global::System.DateTime _Last_AccessTime;
        partial void OnLast_AccessTimeChanging(global::System.DateTime value);
        partial void OnLast_AccessTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EAM_role
        {
            get
            {
                return _EAM_role;
            }
            set
            {
                OnEAM_roleChanging(value);
                ReportPropertyChanging("EAM_role");
                _EAM_role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EAM_role");
                OnEAM_roleChanged();
            }
        }
        private global::System.String _EAM_role;
        partial void OnEAM_roleChanging(global::System.String value);
        partial void OnEAM_roleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CDIS_email
        {
            get
            {
                return _CDIS_email;
            }
            set
            {
                OnCDIS_emailChanging(value);
                ReportPropertyChanging("CDIS_email");
                _CDIS_email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CDIS_email");
                OnCDIS_emailChanged();
            }
        }
        private global::System.String _CDIS_email;
        partial void OnCDIS_emailChanging(global::System.String value);
        partial void OnCDIS_emailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Package_Login", "Package")]
        public EntityCollection<Package> Packages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Package>("tsiewhckweb.Models.FK_Package_Login", "Package");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Package>("tsiewhckweb.Models.FK_Package_Login", "Package", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Machine_Config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Machine_Config : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Machine_Config object.
        /// </summary>
        /// <param name="machineConfigID">Initial value of the MachineConfigID property.</param>
        /// <param name="hW_Version">Initial value of the HW_Version property.</param>
        /// <param name="wHCK_Version">Initial value of the WHCK_Version property.</param>
        /// <param name="windows_Build_Num">Initial value of the Windows_Build_Num property.</param>
        public static Machine_Config CreateMachine_Config(global::System.Int32 machineConfigID, global::System.String hW_Version, global::System.String wHCK_Version, global::System.String windows_Build_Num)
        {
            Machine_Config machine_Config = new Machine_Config();
            machine_Config.MachineConfigID = machineConfigID;
            machine_Config.HW_Version = hW_Version;
            machine_Config.WHCK_Version = wHCK_Version;
            machine_Config.Windows_Build_Num = windows_Build_Num;
            return machine_Config;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MachineConfigID
        {
            get
            {
                return _MachineConfigID;
            }
            set
            {
                if (_MachineConfigID != value)
                {
                    OnMachineConfigIDChanging(value);
                    ReportPropertyChanging("MachineConfigID");
                    _MachineConfigID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MachineConfigID");
                    OnMachineConfigIDChanged();
                }
            }
        }
        private global::System.Int32 _MachineConfigID;
        partial void OnMachineConfigIDChanging(global::System.Int32 value);
        partial void OnMachineConfigIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HW_Version
        {
            get
            {
                return _HW_Version;
            }
            set
            {
                OnHW_VersionChanging(value);
                ReportPropertyChanging("HW_Version");
                _HW_Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HW_Version");
                OnHW_VersionChanged();
            }
        }
        private global::System.String _HW_Version;
        partial void OnHW_VersionChanging(global::System.String value);
        partial void OnHW_VersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WHCK_Version
        {
            get
            {
                return _WHCK_Version;
            }
            set
            {
                OnWHCK_VersionChanging(value);
                ReportPropertyChanging("WHCK_Version");
                _WHCK_Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WHCK_Version");
                OnWHCK_VersionChanged();
            }
        }
        private global::System.String _WHCK_Version;
        partial void OnWHCK_VersionChanging(global::System.String value);
        partial void OnWHCK_VersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Windows_Build_Num
        {
            get
            {
                return _Windows_Build_Num;
            }
            set
            {
                OnWindows_Build_NumChanging(value);
                ReportPropertyChanging("Windows_Build_Num");
                _Windows_Build_Num = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Windows_Build_Num");
                OnWindows_Build_NumChanged();
            }
        }
        private global::System.String _Windows_Build_Num;
        partial void OnWindows_Build_NumChanging(global::System.String value);
        partial void OnWindows_Build_NumChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Test_Config_Machine_Config", "Test_Config")]
        public EntityCollection<Test_Config> Test_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Test_Config>("tsiewhckweb.Models.FK_Test_Config_Machine_Config", "Test_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Test_Config>("tsiewhckweb.Models.FK_Test_Config_Machine_Config", "Test_Config", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Package")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Package : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Package object.
        /// </summary>
        /// <param name="packageID">Initial value of the PackageID property.</param>
        /// <param name="configNumID">Initial value of the ConfigNumID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="checksum">Initial value of the Checksum property.</param>
        /// <param name="date_Uploaded">Initial value of the Date_Uploaded property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="testResult_Summary">Initial value of the TestResult_Summary property.</param>
        public static Package CreatePackage(global::System.Int32 packageID, global::System.Int32 configNumID, global::System.Int32 userID, global::System.String checksum, global::System.DateTime date_Uploaded, global::System.String fileName, global::System.String path, global::System.String testResult_Summary)
        {
            Package package = new Package();
            package.PackageID = packageID;
            package.ConfigNumID = configNumID;
            package.UserID = userID;
            package.Checksum = checksum;
            package.Date_Uploaded = date_Uploaded;
            package.FileName = fileName;
            package.Path = path;
            package.TestResult_Summary = testResult_Summary;
            return package;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PackageID
        {
            get
            {
                return _PackageID;
            }
            set
            {
                if (_PackageID != value)
                {
                    OnPackageIDChanging(value);
                    ReportPropertyChanging("PackageID");
                    _PackageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PackageID");
                    OnPackageIDChanged();
                }
            }
        }
        private global::System.Int32 _PackageID;
        partial void OnPackageIDChanging(global::System.Int32 value);
        partial void OnPackageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfigNumID
        {
            get
            {
                return _ConfigNumID;
            }
            set
            {
                OnConfigNumIDChanging(value);
                ReportPropertyChanging("ConfigNumID");
                _ConfigNumID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConfigNumID");
                OnConfigNumIDChanged();
            }
        }
        private global::System.Int32 _ConfigNumID;
        partial void OnConfigNumIDChanging(global::System.Int32 value);
        partial void OnConfigNumIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Checksum
        {
            get
            {
                return _Checksum;
            }
            set
            {
                OnChecksumChanging(value);
                ReportPropertyChanging("Checksum");
                _Checksum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Checksum");
                OnChecksumChanged();
            }
        }
        private global::System.String _Checksum;
        partial void OnChecksumChanging(global::System.String value);
        partial void OnChecksumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_Uploaded
        {
            get
            {
                return _Date_Uploaded;
            }
            set
            {
                OnDate_UploadedChanging(value);
                ReportPropertyChanging("Date_Uploaded");
                _Date_Uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Uploaded");
                OnDate_UploadedChanged();
            }
        }
        private global::System.DateTime _Date_Uploaded;
        partial void OnDate_UploadedChanging(global::System.DateTime value);
        partial void OnDate_UploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TestResult_Summary
        {
            get
            {
                return _TestResult_Summary;
            }
            set
            {
                OnTestResult_SummaryChanging(value);
                ReportPropertyChanging("TestResult_Summary");
                _TestResult_Summary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TestResult_Summary");
                OnTestResult_SummaryChanged();
            }
        }
        private global::System.String _TestResult_Summary;
        partial void OnTestResult_SummaryChanging(global::System.String value);
        partial void OnTestResult_SummaryChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Package_Login", "Login")]
        public Login Login
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("tsiewhckweb.Models.FK_Package_Login", "Login").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("tsiewhckweb.Models.FK_Package_Login", "Login").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Login> LoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Login>("tsiewhckweb.Models.FK_Package_Login", "Login");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Login>("tsiewhckweb.Models.FK_Package_Login", "Login", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Package_Test_Config", "Test_Config")]
        public Test_Config Test_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Package_Test_Config", "Test_Config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Package_Test_Config", "Test_Config").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Test_Config> Test_ConfigReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Package_Test_Config", "Test_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Package_Test_Config", "Test_Config", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Result_Package", "Result")]
        public EntityCollection<Result> Results
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Result>("tsiewhckweb.Models.FK_Result_Package", "Result");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Result>("tsiewhckweb.Models.FK_Result_Package", "Result", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Project_Group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project_Group : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project_Group object.
        /// </summary>
        /// <param name="project_GroupID">Initial value of the Project_GroupID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="configNumID">Initial value of the ConfigNumID property.</param>
        public static Project_Group CreateProject_Group(global::System.Int32 project_GroupID, global::System.String name, global::System.Int32 configNumID)
        {
            Project_Group project_Group = new Project_Group();
            project_Group.Project_GroupID = project_GroupID;
            project_Group.Name = name;
            project_Group.ConfigNumID = configNumID;
            return project_Group;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Project_GroupID
        {
            get
            {
                return _Project_GroupID;
            }
            set
            {
                if (_Project_GroupID != value)
                {
                    OnProject_GroupIDChanging(value);
                    ReportPropertyChanging("Project_GroupID");
                    _Project_GroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Project_GroupID");
                    OnProject_GroupIDChanged();
                }
            }
        }
        private global::System.Int32 _Project_GroupID;
        partial void OnProject_GroupIDChanging(global::System.Int32 value);
        partial void OnProject_GroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfigNumID
        {
            get
            {
                return _ConfigNumID;
            }
            set
            {
                OnConfigNumIDChanging(value);
                ReportPropertyChanging("ConfigNumID");
                _ConfigNumID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConfigNumID");
                OnConfigNumIDChanged();
            }
        }
        private global::System.Int32 _ConfigNumID;
        partial void OnConfigNumIDChanging(global::System.Int32 value);
        partial void OnConfigNumIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Component_Project_Group", "Component")]
        public EntityCollection<Component> Components
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Component>("tsiewhckweb.Models.FK_Component_Project_Group", "Component");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Component>("tsiewhckweb.Models.FK_Component_Project_Group", "Component", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Project_Group_Test_Config", "Test_Config")]
        public Test_Config Test_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Project_Group_Test_Config", "Test_Config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Project_Group_Test_Config", "Test_Config").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Test_Config> Test_ConfigReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Project_Group_Test_Config", "Test_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Test_Config>("tsiewhckweb.Models.FK_Project_Group_Test_Config", "Test_Config", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Result")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Result : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Result object.
        /// </summary>
        /// <param name="resultID">Initial value of the ResultID property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="comment">Initial value of the Comment property.</param>
        /// <param name="packageID">Initial value of the PackageID property.</param>
        /// <param name="bugID">Initial value of the BugID property.</param>
        /// <param name="testCaseID">Initial value of the TestCaseID property.</param>
        public static Result CreateResult(global::System.Int32 resultID, global::System.Boolean status, global::System.String comment, global::System.Int32 packageID, global::System.Int32 bugID, global::System.Int32 testCaseID)
        {
            Result result = new Result();
            result.ResultID = resultID;
            result.Status = status;
            result.Comment = comment;
            result.PackageID = packageID;
            result.BugID = bugID;
            result.TestCaseID = testCaseID;
            return result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResultID
        {
            get
            {
                return _ResultID;
            }
            set
            {
                if (_ResultID != value)
                {
                    OnResultIDChanging(value);
                    ReportPropertyChanging("ResultID");
                    _ResultID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResultID");
                    OnResultIDChanged();
                }
            }
        }
        private global::System.Int32 _ResultID;
        partial void OnResultIDChanging(global::System.Int32 value);
        partial void OnResultIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Boolean _Status;
        partial void OnStatusChanging(global::System.Boolean value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PackageID
        {
            get
            {
                return _PackageID;
            }
            set
            {
                OnPackageIDChanging(value);
                ReportPropertyChanging("PackageID");
                _PackageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PackageID");
                OnPackageIDChanged();
            }
        }
        private global::System.Int32 _PackageID;
        partial void OnPackageIDChanging(global::System.Int32 value);
        partial void OnPackageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BugID
        {
            get
            {
                return _BugID;
            }
            set
            {
                OnBugIDChanging(value);
                ReportPropertyChanging("BugID");
                _BugID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BugID");
                OnBugIDChanged();
            }
        }
        private global::System.Int32 _BugID;
        partial void OnBugIDChanging(global::System.Int32 value);
        partial void OnBugIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TestCaseID
        {
            get
            {
                return _TestCaseID;
            }
            set
            {
                OnTestCaseIDChanging(value);
                ReportPropertyChanging("TestCaseID");
                _TestCaseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestCaseID");
                OnTestCaseIDChanged();
            }
        }
        private global::System.Int32 _TestCaseID;
        partial void OnTestCaseIDChanging(global::System.Int32 value);
        partial void OnTestCaseIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Result_Bug", "Bug")]
        public Bug Bug
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bug>("tsiewhckweb.Models.FK_Result_Bug", "Bug").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bug>("tsiewhckweb.Models.FK_Result_Bug", "Bug").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bug> BugReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bug>("tsiewhckweb.Models.FK_Result_Bug", "Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bug>("tsiewhckweb.Models.FK_Result_Bug", "Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Result_Package", "Package")]
        public Package Package
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Package>("tsiewhckweb.Models.FK_Result_Package", "Package").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Package>("tsiewhckweb.Models.FK_Result_Package", "Package").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Package> PackageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Package>("tsiewhckweb.Models.FK_Result_Package", "Package");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Package>("tsiewhckweb.Models.FK_Result_Package", "Package", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Result_TestCase", "TestCase")]
        public TestCase TestCase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestCase>("tsiewhckweb.Models.FK_Result_TestCase", "TestCase").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestCase>("tsiewhckweb.Models.FK_Result_TestCase", "TestCase").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TestCase> TestCaseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestCase>("tsiewhckweb.Models.FK_Result_TestCase", "TestCase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TestCase>("tsiewhckweb.Models.FK_Result_TestCase", "TestCase", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="Test_Config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test_Config : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test_Config object.
        /// </summary>
        /// <param name="configNumID">Initial value of the ConfigNumID property.</param>
        /// <param name="machineConfigID">Initial value of the MachineConfigID property.</param>
        /// <param name="driverConfigID">Initial value of the DriverConfigID property.</param>
        public static Test_Config CreateTest_Config(global::System.Int32 configNumID, global::System.Int32 machineConfigID, global::System.Int32 driverConfigID)
        {
            Test_Config test_Config = new Test_Config();
            test_Config.ConfigNumID = configNumID;
            test_Config.MachineConfigID = machineConfigID;
            test_Config.DriverConfigID = driverConfigID;
            return test_Config;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfigNumID
        {
            get
            {
                return _ConfigNumID;
            }
            set
            {
                if (_ConfigNumID != value)
                {
                    OnConfigNumIDChanging(value);
                    ReportPropertyChanging("ConfigNumID");
                    _ConfigNumID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConfigNumID");
                    OnConfigNumIDChanged();
                }
            }
        }
        private global::System.Int32 _ConfigNumID;
        partial void OnConfigNumIDChanging(global::System.Int32 value);
        partial void OnConfigNumIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MachineConfigID
        {
            get
            {
                return _MachineConfigID;
            }
            set
            {
                OnMachineConfigIDChanging(value);
                ReportPropertyChanging("MachineConfigID");
                _MachineConfigID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MachineConfigID");
                OnMachineConfigIDChanged();
            }
        }
        private global::System.Int32 _MachineConfigID;
        partial void OnMachineConfigIDChanging(global::System.Int32 value);
        partial void OnMachineConfigIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DriverConfigID
        {
            get
            {
                return _DriverConfigID;
            }
            set
            {
                OnDriverConfigIDChanging(value);
                ReportPropertyChanging("DriverConfigID");
                _DriverConfigID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DriverConfigID");
                OnDriverConfigIDChanged();
            }
        }
        private global::System.Int32 _DriverConfigID;
        partial void OnDriverConfigIDChanging(global::System.Int32 value);
        partial void OnDriverConfigIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Test_Config_Driver_Config", "Driver_Config")]
        public Driver_Config Driver_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver_Config>("tsiewhckweb.Models.FK_Test_Config_Driver_Config", "Driver_Config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver_Config>("tsiewhckweb.Models.FK_Test_Config_Driver_Config", "Driver_Config").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Driver_Config> Driver_ConfigReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver_Config>("tsiewhckweb.Models.FK_Test_Config_Driver_Config", "Driver_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Driver_Config>("tsiewhckweb.Models.FK_Test_Config_Driver_Config", "Driver_Config", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Test_Config_Machine_Config", "Machine_Config")]
        public Machine_Config Machine_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Machine_Config>("tsiewhckweb.Models.FK_Test_Config_Machine_Config", "Machine_Config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Machine_Config>("tsiewhckweb.Models.FK_Test_Config_Machine_Config", "Machine_Config").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Machine_Config> Machine_ConfigReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Machine_Config>("tsiewhckweb.Models.FK_Test_Config_Machine_Config", "Machine_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Machine_Config>("tsiewhckweb.Models.FK_Test_Config_Machine_Config", "Machine_Config", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Package_Test_Config", "Package")]
        public EntityCollection<Package> Packages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Package>("tsiewhckweb.Models.FK_Package_Test_Config", "Package");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Package>("tsiewhckweb.Models.FK_Package_Test_Config", "Package", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Project_Group_Test_Config", "Project_Group")]
        public EntityCollection<Project_Group> Project_Group
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project_Group>("tsiewhckweb.Models.FK_Project_Group_Test_Config", "Project_Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project_Group>("tsiewhckweb.Models.FK_Project_Group_Test_Config", "Project_Group", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tsiewhckweb.Models", Name="TestCase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestCase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestCase object.
        /// </summary>
        /// <param name="testCaseID">Initial value of the TestCaseID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="componentID">Initial value of the ComponentID property.</param>
        /// <param name="timeStamp">Initial value of the TimeStamp property.</param>
        public static TestCase CreateTestCase(global::System.Int32 testCaseID, global::System.String name, global::System.Int32 componentID, global::System.DateTime timeStamp)
        {
            TestCase testCase = new TestCase();
            testCase.TestCaseID = testCaseID;
            testCase.Name = name;
            testCase.ComponentID = componentID;
            testCase.TimeStamp = timeStamp;
            return testCase;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TestCaseID
        {
            get
            {
                return _TestCaseID;
            }
            set
            {
                if (_TestCaseID != value)
                {
                    OnTestCaseIDChanging(value);
                    ReportPropertyChanging("TestCaseID");
                    _TestCaseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TestCaseID");
                    OnTestCaseIDChanged();
                }
            }
        }
        private global::System.Int32 _TestCaseID;
        partial void OnTestCaseIDChanging(global::System.Int32 value);
        partial void OnTestCaseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComponentID
        {
            get
            {
                return _ComponentID;
            }
            set
            {
                OnComponentIDChanging(value);
                ReportPropertyChanging("ComponentID");
                _ComponentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComponentID");
                OnComponentIDChanged();
            }
        }
        private global::System.Int32 _ComponentID;
        partial void OnComponentIDChanging(global::System.Int32 value);
        partial void OnComponentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private global::System.DateTime _TimeStamp;
        partial void OnTimeStampChanging(global::System.DateTime value);
        partial void OnTimeStampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_TestCase_Component", "Component")]
        public Component Component
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Component>("tsiewhckweb.Models.FK_TestCase_Component", "Component").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Component>("tsiewhckweb.Models.FK_TestCase_Component", "Component").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Component> ComponentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Component>("tsiewhckweb.Models.FK_TestCase_Component", "Component");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Component>("tsiewhckweb.Models.FK_TestCase_Component", "Component", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tsiewhckweb.Models", "FK_Result_TestCase", "Result")]
        public EntityCollection<Result> Results
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Result>("tsiewhckweb.Models.FK_Result_TestCase", "Result");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Result>("tsiewhckweb.Models.FK_Result_TestCase", "Result", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
