//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace tsiewhckweb.Models
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tsiewhckwebEntities : DbContext
    {
        static tsiewhckwebEntities()
    	{ 
    		Database.SetInitializer<tsiewhckwebEntities>(null);
    	}
    	
    	public tsiewhckwebEntities() : base("name=tsiewhckwebEntities")
        {
        }
    	
    	public tsiewhckwebEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public tsiewhckwebEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public tsiewhckwebEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public tsiewhckwebEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new Bug_Mapping());
    		modelBuilder.Configurations.Add(new Component_Mapping());
    		modelBuilder.Configurations.Add(new Driver_Config_Mapping());
    		modelBuilder.Configurations.Add(new Login_Mapping());
    		modelBuilder.Configurations.Add(new Machine_Config_Mapping());
    		modelBuilder.Configurations.Add(new Package_Mapping());
    		modelBuilder.Configurations.Add(new Project_Group_Mapping());
    		modelBuilder.Configurations.Add(new Result_Mapping());
    		modelBuilder.Configurations.Add(new Test_Config_Mapping());
    		modelBuilder.Configurations.Add(new TestCase_Mapping());
        }
    	
        public DbSet<Bug> Bugs { get; set; }
        public DbSet<Component> Components { get; set; }
        public DbSet<Driver_Config> Driver_Config { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Machine_Config> Machine_Config { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<Project_Group> Project_Group { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Test_Config> Test_Config { get; set; }
        public DbSet<TestCase> TestCases { get; set; }
    }
}
